# DataSource Config
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    url: jdbc:p6spy:h2:mem:test
    username: root
    password: test
  # 启用H2 Web Console http://localhost:8080/h2-console
  h2:
    console:
      enabled: on
      path: /h2
      settings:
        web-allow-others: on


# Logger Config
logging:
  level:
    com.peng.mybatisplus: debug
# MyBatis-Plus 配置该演示无
